/* eslint-env cypress */
describe('Nawigacja oraz tłumaczenia na stronie głównej', () => {
  it('Przesuwa ekran do sekcji technologia', () => {
    cy.visit('/')
    cy.contains(/Technologia|Technology/).click()
    cy.url().should('include', '/')
    cy.contains(
      /Technology for your health air under control|Technologia dla twojego zdrowia powietrze pod kontrolą/,
    ).should('be.visible')
  })
  it('Sprawdza czy zmiana języka działa', () => {
    cy.visit('/')
    cy.get('div.cursor-pointer').contains('PL').click()
    cy.contains('Planning trips and leisure has never been easier.').should('be.visible')
    cy.get('div.cursor-pointer').contains('EN').click()
    cy.contains('Planowanie wyjazdów i wypoczynku nigdy nie było prostsze.').should('be.visible')
  })
  it('Sprawdza czy wszystkie zakładki FAQ się rozwiją', () => {
    cy.visit('/')
    cy.get(':nth-child(1) > .q-expansion-item__container > .q-item').click()
    cy.contains(
      'Tak, AirSense Gdańsk to projekt non-profit poprawiający jakość życia mieszkańców.',
    ).should('be.visible')
    cy.get(':nth-child(2) > .q-expansion-item__container > .q-item').click()
    cy.contains('Tak, obsługujemy wiele języków dla większej dostępności.').should('be.visible')
    cy.get(':nth-child(3) > .q-expansion-item__container > .q-item').click()
    cy.contains('Nie. Nie zbieramy danych i nie wymagamy konta.').should('be.visible')
    cy.get(':nth-child(4) > .q-expansion-item__container > .q-item').click()
    cy.contains('Obecnie dostępna na komputerach. Wersja mobilna w planach.').should('be.visible')
    cy.get(':nth-child(5) > .q-expansion-item__container > .q-item').click()
    cy.contains('Codziennie. Korzystamy z wiarygodnych i monitorowanych źródeł danych.').should(
      'be.visible',
    )
  })
  it('Sprawdza czy wszystkie zdjęcia na stronie poprawnie się załadowały', () => {
    cy.visit('/')
    cy.get('img').each(($el) => {
      cy.get(':nth-child(4) > img').should('be.visible')
      cy.get('[style="background-color: rgb(250, 250, 250);"] > .col-12 > .col-xs-12 > img').should(
        'be.visible',
      )
      cy.get('.col-md-6 > img').should('be.visible')
    })
  })
  it('Sprawdza czy można przechodzić pomiędzy mapą a stroną główna niezalogowanego użytkownika oraz czy wysuwa się panel mapy', () => {
    cy.visit('/')
    cy.get('div.cursor-pointer').contains('Mapa').click()
    cy.url().should('include', '/map')
    cy.get('.column > .row > .q-icon').should('be.visible')
    cy.get('.column > .row > .q-icon').click()
    cy.get('.panel-content').should('be.visible')
    cy.wait(500)
    cy.get('[style="font-size: 45px; text-align: center;"]').should('be.visible')
    cy.get('[style="font-size: 45px; text-align: center;"] > .q-mt-md').click()
    cy.url().should('include', '/')
  })
  it('Sprawdza czy tłumaczenia na strony mapy działają poprawnie', () => {
    cy.visit('/map')
    cy.get('.column > .row > .q-icon').should('be.visible')
    cy.get('.column > .row > .q-icon').click()
    cy.get('.panel-content').should('be.visible')
    cy.contains('Wybierz zakres').should('be.visible')
    cy.contains('Wybierz parametry pogody').should('be.visible')
    cy.get('[title="English"]').should('be.visible')
    cy.get('[title="English"]').click()
    cy.contains('Select range').should('be.visible')
    cy.contains('Select weather parameters').should('be.visible')
  })
})

describe('Nawigacja,dodatkowe funkcjonalności oraz tłumaczenia na stronie zalogowanego użytkownika: WYMAGAGA LOGOWANIA RECZNEGO NA KONTO GOOGLE', () => {
  it('Sprawdza czy zalogowany użytkownik poprawnie przenosi się po zakładkach w drawlerze', () => {
    cy.visit('/main')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(2)').should('be.visible')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(2)').click()
    cy.url().should('include', '/main/map')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(3)').should('be.visible')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(3)').click()
    cy.url().should('include', 'main/locations')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(4)').should('be.visible')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(4)').click()
    cy.url().should('include', '/main/raports')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(1)').should('be.visible')
    cy.get('.drawer-container > :nth-child(2) > :nth-child(1)').click()
    cy.url().should('include', '/main')
  })
  it('Sprawdza czy zalogowany użytkownik widzi poprawnie wykresy oraz mapę', () => {
    cy.visit('/main')
    cy.get(':nth-child(1) > .vue-apexcharts').should('exist').and('be.visible')
    cy.get(':nth-child(2) > .vue-apexcharts').should('exist').and('be.visible')
    cy.get('[style="height: 300px; margin-bottom: 40px;"] > .vue-apexcharts')
      .should('exist')
      .and('be.visible')
  })
  it('Sprawdza czy zalogowany użytkownik widzi poprawnie wykresy oraz mapę', () => {
    cy.visit('/main')
    cy.get(':nth-child(1) > .vue-apexcharts').should('exist').and('be.visible')
    cy.get(':nth-child(2) > .vue-apexcharts').should('exist').and('be.visible')
    cy.get('[style="height: 300px; margin-bottom: 40px;"] > .vue-apexcharts')
      .should('exist')
      .and('be.visible')
  })
  it('Sprawdza czy zalogowany użytkownik może otworzyć edytor do tworzenia ulubionej lokalizacji oraz wprowadzić dane', () => {
    cy.visit('/main/locations')
    cy.get('.q-btn')
      .contains(/Utwórz lokalizację|Create location/)
      .should('exist')
      .and('be.visible')
    cy.get('.q-btn')
      .contains(/Utwórz lokalizację|Create location/)
      .click()
    cy.get(':nth-child(1) > .col-12 > .q-field > .q-field__inner > .q-field__control')
      .should('exist')
      .and('be.visible')
    cy.get(':nth-child(1) > .col-12 > .q-field > .q-field__inner > .q-field__control').type(
      'Testowa lokalizacja',
    )
    cy.get(':nth-child(2) > div.col-12 > .q-field > .q-field__inner > .q-field__control')
      .should('exist')
      .and('be.visible')
    cy.get(':nth-child(2) > div.col-12 > .q-field > .q-field__inner > .q-field__control').type(
      'Testowy opis',
    )
    cy.get('.leaflet-container').should('exist').and('be.visible')
    cy.get('.leaflet-container').click(200, 200)
    cy.get('.bg-primary').should('exist').and('be.visible')
    cy.get('.bg-primary').click()
  })
  it('Sprawdza czy zalogowany użytkownik może wprowadzic dane i utworzyć raport ', () => {
    cy.visit('/main/raports')
    cy.get('[style="flex: 1 1 0%; margin-right: 20px;"]')
      .contains(/Dzień|Day/)
      .should('be.visible')
    cy.get('[style="flex: 1 1 0%; margin-right: 20px;"]').click()
    cy.get(':nth-child(1) > .q-field > .q-field__inner > .q-field__control').click()
    cy.get('.q-item')
      .contains(/Wilgotność|Humidity/)
      .click()
    cy.get(':nth-child(1) > .q-field > .q-field__inner > .q-field__control').click()
    cy.get(
      '.customclassfirst > .q-field > .q-field__inner > .q-field__control > .q-field__append > .q-icon > img',
    )
      .should('exist')
      .and('be.visible')
      .click()
    cy.get('.q-date__calendar-days > :nth-child(4) > .q-btn')
      .should('exist')
      .and('be.visible')
      .click()
    cy.get('.customclasssecond > .q-field > .q-field__inner > .q-field__control')
      .should('exist')
      .and('be.visible')
      .type('2025-05-23')
    cy.get('.col-8 > .q-card > .col-12 > [style="font-size: 15px;"]')
      .should('exist')
      .and('be.visible')
      .click()
    cy.get('.leaflet-container').click(200, 200)
    cy.get('.justify-between > .q-btn')
      .contains(/Wygeneruj dane|Generate Data/)
      .should('exist')
      .and('be.visible')
      .click()
  })
})
